export const activityIdeas = {
  level1: [
    "Take a walk in the park",
    "Read a book",
    "Cook a new recipe",
    "Watch a movie",
    "Visit a museum",
    "Go for a bike ride",
    "Do a puzzle",
    "Try a new hobby",
    "Write in a journal",
    "Listen to a podcast",
    "Do some gardening",
    "Go for a swim",
    "Have a picnic",
    "Visit a friend",
    "Do some yoga",
    "Go to a farmer's market",
    "Try a new type of tea or coffee",
    "Take a relaxing bath",
    "Make a scrapbook",
    "Create a vision board",
    "Plan a dream vacation",
    "Learn how to juggle",
    "Do a random act of kindness",
    "Make a list of things you're grateful for",
    "Practice meditation for 10 minutes",
    "Rearrange your furniture",
    "Call a family member you haven’t spoken to in a while",
    "Walk around your neighborhood with no destination",
    "Create a playlist for different moods",
    "Write a letter to your future self",
    "Learn how to fold origami",
    "Explore a nearby park you’ve never been to",
    "Visit a local café and try something new",
    "Start a budget tracker",
    "Try to make a new recipe from a different culture",
    "Sketch something you see outside",
    "Have a movie marathon of a particular genre",
    "Go to a bookstore and browse the aisles for an hour",
    "Make a DIY gift for someone",
    "Start a bullet journal",
    "Volunteer at a local charity",
    "Make a playlist of your favorite childhood songs",
    "Revisit an old hobby you used to enjoy",
    "Take a photography walk in your neighborhood",
    "Practice a new language for 30 minutes",
    "Try a new workout routine",
    "Set a goal and write down the steps to achieve it",
    "Do some spring cleaning and donate items you no longer use",
    "Make your own candles or soap"
  ],
  level2: [
    "Try a random food you've never had",
    "Go to a coffee shop and people-watch",
    "Talk to a stranger for 5 minutes",
    "Dance to a song in the middle of your living room",
    "Take a nap in a hammock",
    "Start learning a new language for 30 minutes",
    "Attempt a DIY project you’ve never done",
    "Do a random act of kindness",
    "Go to a park and feed the birds",
    "Learn a magic trick",
    "Try a new sport for the first time",
    "Go to an escape room with friends",
    "Make a short video for TikTok or Instagram",
    "Buy something from a thrift store that you never thought you'd own",
    "Write a short story in 10 minutes",
    "Do 5 random push-ups every time you check the time",
    "Take a photo of the sunset and share it",
    "Go to a new part of your city you've never visited",
    "Host a themed dinner with friends",
    "Try a new hairstyle",
    "Have a 'tech-free' day",
    "Write a poem about your current mood",
    "Make a vision board for your goals",
    "Create a time-lapse video of your day",
    "Visit a local landmark you’ve never been to",
    "Learn to tie a new knot",
    "Have a one-on-one conversation with someone you don't know well",
    "Try a new board game or card game",
    "Start a gratitude journal",
    "Take a photo every hour for a day",
    "Play a sport you haven't played in a long time",
    "Host a karaoke session with friends",
    "Try to complete a puzzle in one sitting",
    "Create a DIY craft project",
    "Join a virtual class or workshop",
    "Find a new podcast to listen to",
    "Make a collage of your favorite quotes",
    "Attend a local event you haven’t experienced before",
    "Create a bucket list for the year",
    "Go to a zoo or aquarium",
    "Try indoor rock climbing",
    "Make a list of your favorite childhood memories",
    "Start a vision or goal board for the next year",
    "Join a book club or online reading group",
    "Volunteer for a community event",
    "Watch a documentary on something you know little about"
  ],
  level3: [
    "Go to a thrift store and buy the weirdest thing you can find",
    "Dress up in a costume and go grocery shopping",
    "Write a letter to your future self",
    "Draw a self-portrait using only your non-dominant hand",
    "Start a random online poll about something quirky",
    "Send a postcard to a friend you haven’t talked to in a while",
    "Record yourself singing your favorite song and post it online",
    "Do a silly walk through your neighborhood",
    "Create an absurd social media post with no context",
    "Have a silent disco by yourself in your room",
    "Make a collage of random things you find around your house",
    "Go to a public park and give out free high-fives",
    "Create a short skit with your friends and post it online",
    "Create a themed playlist for different occasions",
    "Go to a movie theater and wear a superhero costume",
    "Start a conversation in public with a completely made-up accent",
    "Pretend you are a news anchor and report on your day",
    "Take an old-fashioned photo with a disposable camera",
    "Make a scrapbook of your favorite memes",
    "Pick a random object and make up a backstory for it",
    "Spend a day living like it's the 1980s",
    "Make a video of yourself doing a tutorial for something ridiculous",
    "Play a prank on a friend or family member",
    "Start a hashtag for something totally random",
    "Draw a cartoon version of yourself and share it online",
    "Go to a coffee shop and give out compliments to strangers",
    "Try to convince someone to do something silly",
    "Make a YouTube video trying to teach an odd skill",
    "Make a list of things to do that make absolutely no sense",
    "Send an email to a random person with a weird question",
    "Pretend to be a tourist in your own city and take photos",
    "Do an interpretive dance in public",
    "Have a conversation with yourself as if you're two different people",
    "Try to create a trend and get people to follow it",
    "Write a rap about your day and perform it",
    "Do a roleplay of being a famous character for the day",
    "Record a public service announcement about something random",
    "Pretend to be an actor in a movie scene for a day",
    "Take a random walk and count the number of steps until you stop",
    "Make a 10-minute vlog about nothing in particular",
    "Try to make a perfect sandwich with the weirdest ingredients",
    "Go to a fast food joint and ask for a 'secret menu' item"
  ],
  level4: [
    "Try to make a hat out of everyday objects",
    "Write a short story using only words that start with 'S'",
    "Create a mini treasure hunt for your friends",
    "Pretend you're a character in a movie for an entire day",
    "Give yourself a new name and introduce yourself to people with it",
    "Go to a mall and pretend to be a mannequin for 10 minutes",
    "Create a weird invention using only household items",
    "Invent a new handshake and teach it to someone",
    "Host a mini cooking competition with friends",
    "Host a random 'fashion show' with your clothes",
    "Pretend to be an artist for a day and create 'abstract' art",
    "Make a list of impossible goals and try to accomplish them",
    "Go to a pet store and pretend to be the manager",
    "Host a random trivia night with no preparation",
    "Record yourself reading a dramatic grocery list out loud",
    "Create a parody of a popular TV show or movie scene",
    "Go to a random location and pretend you're on a secret mission",
    "Host an improv comedy show with friends",
    "Find an old childhood toy and reimagine its purpose",
    "Go to a movie theater and act like the character you're watching",
    "Start an impromptu dance party in a public space",
    "Go outside and randomly yell 'Plot twist!' every few minutes",
    "Pretend you’re from another country and try to fit in",
    "Take a public transport ride dressed as a professional wrestler",
    "Make a 'fake' commercial for an absurd product",
    "Create a board game using only things you find in your house",
    "Pretend you're an undercover agent and conduct a covert mission",
    "Make a mockumentary about an everyday object",
    "Pick an everyday activity and do it in slow motion",
    "Pick a theme and go to a public space wearing a related costume",
    "Host a food tasting of only foods you dislike",
    "Go to a store and ask the staff about their most absurd item",
    "Have a 'backwards' dinner with dessert first",
    "Start a spontaneous conga line in a public place",
    "Set up a booth for 'free hugs' in a crowded place",
    "Create a treasure map and pretend you're on a pirate adventure",
    "Perform a magic trick for a stranger and see if they believe it"
  ],
    level5: [
      "Start a flash mob in a public place with your friends",
      "Invent a fictional band and perform a concert for strangers",
      "Write a fake history book about an imaginary character",
      "Make a fake conspiracy theory and try to convince people it's true",
      "Try to communicate only using animal sounds for an hour",
      "Host a fictional talent show where no one can perform",
      "Make up fake life advice and give it to strangers",
      "Pretend you're a superhero saving the world in a coffee shop",
      "Start a fake detective agency and try to solve mysterious 'cases'",
      "Pretend you're a famous artist and 'accidentally' create a masterpiece",
      "Create a fake documentary about a random object",
      "Challenge people to 'disappear' in plain sight",
      "Try to convince someone you have a secret identity",
      "Host a fake cooking competition with absolutely no ingredients",
      "Write a letter from the future and send it to a friend",
      "Invent a fake holiday and celebrate it with friends",
      "Start a campaign to make your made-up language the official one",
      "Ask strangers for help with a fictional project you’re working on"
    ],
    level6: [
      "Go to a public event and act like you're supposed to be in charge",
      "Start an underground movement for something absurd",
      "Create a fake news report about something that doesn’t exist",
      "Try to get people to follow a made-up trend",
      "Pretend to be a time traveler from the past and explain modern technology",
      "Host a fake press conference for a made-up scandal",
      "Go to a shopping mall and convince people you're a celebrity",
      "Write a letter of complaint to a fictional company and post it online",
      "Create a fake social media account for an imaginary pet",
      "Make a movie trailer for a completely absurd concept",
      "Pretend to be a famous detective solving an everyday problem",
      "Create an outlandish scientific theory and present it to a group",
      "Go to a public space and offer ‘free advice’ on something ridiculous",
      "Record a serious podcast about something totally random",
      "Start a pretend charity and try to get people to support it",
      "Have a conversation using only movie quotes",
      "Pretend to be an astronaut explaining life on Mars",
      "Host a talent show where all the acts are terrible on purpose",
      "Create a bizarre fashion trend and see how many people follow it",
      "Have a conversation with a stranger using only made-up words"
    ],
    level7: [
      "Set up a booth for ‘free advice’ that makes no sense",
      "Go to a store and start selling invisible products",
      "Start an improv comedy show in the middle of a crowded street",
      "Pretend to be a movie director and give random people on the street acting instructions",
      "Throw a fake award ceremony for made-up achievements",
      "Go to a public space and shout out the rules of an absurd game",
      "Invent a new type of dance and teach it to strangers",
      "Start a fake political campaign for an invisible candidate",
      "Ask people to sign a petition for an imaginary cause",
      "Do a flash interview with strangers, asking them absurd questions",
      "Create a fake infomercial for a ridiculous product",
      "Hold a fake 'silent auction' for something that doesn’t exist",
      "Pretend to be a time traveler and tell people you're stuck in their era",
      "Start an impromptu book club on the street, reading from a fake book",
      "Do a live-stream of a random, uninteresting task as if it’s the most important event",
      "Pretend to be a secret agent on a mission and involve random strangers",
      "Create a fake archaeological dig in your backyard and present it as a discovery",
      "Perform a flash performance of a fictional play in a park",
      "Go to a popular café and pretend to be a local reporter",
      "Convince strangers to help you with an absurd invention"
    ],
    level8: [
      "Dress up as a famous historical figure and start talking to strangers about your past",
      "Create a fake social experiment and ask people to participate without explaining",
      "Act as a professional critic and review random objects in public",
      "Start a fake reality TV show where the only challenge is to stand still",
      "Host a random impromptu parade in your neighborhood",
      "Create a website for a made-up product and try to convince people to buy it",
      "Pretend to be a famous author and give a fake book reading",
      "Host a pretend cooking show in a public park with no ingredients",
      "Create a fake app and ask strangers to download it",
      "Start an entirely made-up holiday and ask people to participate",
      "Invent a new sport and start playing it in a park with no rules",
      "Go to a mall dressed as a wizard and offer free magical advice",
      "Write a letter to a famous celebrity, asking them for random advice",
      "Make a fake biography for a random person and share it online",
      "Pretend to be a celebrity chef and give cooking advice in a grocery store",
      "Start a new fictional religion and try to get followers",
      "Ask strangers to help you search for a made-up lost item",
      "Create a fake online store selling things that don't exist",
      "Host a mock debate between two completely made-up political parties",
      "Pretend you are a famous inventor and demonstrate your latest 'invention'"
    ],
    level9: [
      "Start a fake UFO cult and convince people to join",
      "Organize a flash wedding in a public space for no reason",
      "Create a fake time capsule and try to convince strangers to contribute to it",
      "Stage an impromptu protest for a completely bizarre cause",
      "Host a fake talk show and interview strangers about nothing",
      "Send out invitations for a fake, imaginary event and see who shows up",
      "Set up a fake pet adoption booth for completely made-up animals",
      "Throw an outdoor picnic where the only food is imaginary",
      "Host a 'Survivor' game in the middle of a mall for random people",
      "Create a fake celebrity and try to convince people you know them",
      "Start a rumor in a public place and watch it spread",
      "Pretend you are the world's greatest detective and solve fake mysteries",
      "Go to a supermarket dressed as a superhero and 'save' people from buying the wrong items",
      "Create a fake scientific breakthrough and try to pitch it to people",
      "Invent a fake workout routine and teach it to strangers in a park",
      "Start a flash news broadcast on the street about a made-up emergency",
      "Convince a group of people to participate in a completely fake competition",
      "Stage a fake wedding proposal and see how people react",
      "Create an online forum for discussing made-up topics and get people to join",
      "Host a fake podcast recording in a public space and invite strangers to participate"
    ],
    level10: [
      "Start a fake alien invasion in the middle of a crowded area",
      "Host a fake underground concert and get people to follow you",
      "Go to a public park and pretend to be a famous movie star for a day",
      "Start an underground game of tag with random strangers",
      "Create a fake historical event and pitch it as truth to a news outlet",
      "Pretend you're a character from the future and give random advice to people",
      "Send out fake press releases for completely fabricated events",
      "Get strangers to join in on an impromptu play with no script",
      "Throw a party with no reason and invite only random strangers",
      "Create a fake identity and try to convince people you’re someone important",
      "Create an entire fake city with its own rules and try to get people to follow them",
      "Pretend to be a superhero and start fighting crime in a public place",
      "Start an underground language movement and try to get people to join it",
      "Make a fake historical monument and try to get people to believe it",
      "Pretend you're a famous archaeologist and stage an excavation in a park",
      "Start a fake tech startup and pitch it to investors",
      "Pretend to be an influencer and go live on social media doing absurd things",
      "Create a fake 'zoo' with random objects and charge people to visit",
      "Pretend to be a mad scientist and create a fake invention in a public space",
      "Host a fake 'game show' with absurd challenges for random participants",
      "Go outside and pretend you're in the 1800s."
    ]
  };
